variables:
    GIT_DEPTH: "1"

stages:
    - develop_build
    - release_build
    - prepare_develop_debs
    - prepare_release_debs

develop_build:
    tags:
        - Runner-Stretch
    stage: develop_build
    except:
      refs:
        - stretch
    script:
        - dpkg-buildpackage -us -uc -b
        - mv ../*.deb .
    artifacts:
        name: "${CI_PROJECT_NAME}"
        paths:
        - ./*.deb

release_build:
    tags:
        - Runner-Stretch
    stage: release_build
    only:
      refs:
        - stretch
    script:
        - dpkg-buildpackage -us -uc -b
        - mv ../*.deb .
    artifacts:
        name: "${CI_PROJECT_NAME}"
        paths:
        - ./*.deb

prepare_develop_debs:
    tags:
        - Runner-Stretch
    stage: prepare_develop_debs
    only:
      refs:
        - stretch-develop
    dependencies:
        - develop_build
    script:
        - mkdir -p /cache/stretch/develop/
        - cp *.deb /cache/stretch/develop/
        - ls /cache/stretch/develop/

prepare_release_debs:
    tags:
        - Runner-Stretch
    stage: prepare_release_debs
    only:
      refs:
        - stretch
    dependencies:
        - release_build
    script:
        - mkdir -p /cache/stretch/release/
        - cp *.deb /cache/stretch/release/
        - ls /cache/stretch/release/