#!/bin/bash

READFILE="/etc/moxa-configs/moxa-firmware-tools.conf"
MOXA_INIT_UPGRADE_FILE="/overlayfs/moxa-init"
MOXA_INIT_FILE="/sbin/moxa-init"

upgrade_moxa_init () {
	# check moxa-init-main
	if [ -f "$MOXA_INIT_UPGRADE_FILE" ]; then
		echo "Found a new version of moxa-init, updating..."
		mv "$MOXA_INIT_UPGRADE_FILE" "$MOXA_INIT_FILE"
		echo "Update moxa-init successful"
	fi
}

upgrade_moxa_init

# get flag from spi flash
eval "$(fw_printenv|grep overlay_flag)"

# check overlay flag is exist or not
if [ x"$overlay_flag" == x"" ]; then
	fw_setenv overlay_flag v1
	overlay_flag="v1"
fi

# Engineer debug mode
if [ x"$overlay_flag" == x"debug" ]; then
	exec /lib/systemd/systemd $@
	exit
fi

# ----- flag=default -----
if [ x"$overlay_flag" == x"default" ]; then
	rm -rf /overlayfs/v1
	if [ -d /overlayfs/default ]; then
		cp -a /overlayfs/default /overlayfs/v1
	fi
	sync
	echo "*****************************" > /dev/ttyS0
	echo "* Set to default successful *" > /dev/ttyS0
	echo "*****************************" > /dev/ttyS0
	fw_setenv overlay_flag v1
fi

# ----- Run overlayfs -----
while read DIR; do
	if [ x"${DIR:0:1}" != x"#" ]&&[ x"${DIR:0:1}" != x"" ] ; then
		/sbin/mx-overlay $DIR
	fi
done < $READFILE

mount -o remount,ro /

# ----- Execute systemd -----
exec /lib/systemd/systemd $@

