#!/bin/bash

READFILE="/etc/moxa-configs/moxa-firmware-tools.conf"

mount -o remount,rw /

# get flag from spi flash
eval "$(fw_printenv|grep overlay_flag)"

# check overlay flag is exist or not
if [ x"$overlay_flag" == x"" ]; then
        fw_setenv overlay_flag v1
        overlay_flag="v1"
fi

# Engineer debug mode
if [ x"$overlay_flag" == x"debug" ]; then
	exec /lib/systemd/systemd $@
	exit
fi

# Get RFS partition from cmdline. e.g. /dev/mmcblk0p2
#ROOT_PART=$(cat /proc/cmdline)
ROOT_PART=$(dmesg | grep "Kernel command line")
ROOT_PART="${ROOT_PART##*root=}"
ROOT_PART="${ROOT_PART%% *}"
ROOT_PART="${ROOT_PART%%2}3"

# mount RFS partition3 to /overlayfs
if [ ! -d /overlayfs ]; then
	mkdir /overlayfs
fi
mount $ROOT_PART /overlayfs

# ----- flag=v1backup -----
if [ x"$overlay_flag" == x"v1backup" ]; then
	rm -rf /overlayfs/v1
	cp -ar /overlayfs/backup /overlayfs/v1
	sync
	fw_setenv overlay_flag v1
	echo "******************" > /dev/ttyS0
	echo "* Upgrade failed *" > /dev/ttyS0
	echo "******************" > /dev/ttyS0
	reboot
	exit
fi

# ----- flag=v0 -----
if [ x"$overlay_flag" == x"v0" ]; then
	echo "****************************" > /dev/ttyS0
	echo "* Restore downgrade status *" > /dev/ttyS0
	echo "****************************" > /dev/ttyS0
	rm -rf /overlayfs/v0
	cp -ar /overlayfs/backup /overlayfs/v0
	sync
	fw_setenv overlay_flag v1d
	reboot
	exit
fi

# ----- flag=v3 -----
if [ x"$overlay_flag" == x"v3" ]; then
	echo "**************************" > /dev/ttyS0
	echo "* Restore upgrade status *" > /dev/ttyS0
	echo "**************************" > /dev/ttyS0
	rm -rf /overlayfs/v0
	cp -ar /overlayfs/backup /overlayfs/v0
	sync
	fw_setenv overlay_flag v1u
	reboot
	exit
fi

# ----- flag=v1u -----
if [ x"$overlay_flag" == x"v1u" ]; then
	rm -rf /overlayfs/backup
	sync
	echo "**********************" > /dev/ttyS0
	echo "* Upgrade successful *" > /dev/ttyS0
	echo "**********************" > /dev/ttyS0
	fw_setenv overlay_flag v1
fi

# ----- flag=v1d -----
if [ x"$overlay_flag" == x"v1d" ]; then
	rm -rf /overlayfs/backup
	sync
	echo "************************" > /dev/ttyS0
	echo "* downgrade successful *" > /dev/ttyS0
	echo "************************" > /dev/ttyS0
	fw_setenv overlay_flag v1
fi

# ----- flag=default -----
if [ x"$overlay_flag" == x"default" ]; then
	rm -rf /overlayfs/v1
	if [ -d /overlayfs/default ]; then
		cp -ar /overlayfs/default /overlayfs/v1
	fi
	sync
	echo "*****************************" > /dev/ttyS0
	echo "* Set to default successful *" > /dev/ttyS0
	echo "*****************************" > /dev/ttyS0
	fw_setenv overlay_flag v1
fi

# ----- Run overlayfs -----
while read DIR; do
	if [ x"${DIR:0:1}" != x"#" ]&&[ x"${DIR:0:1}" != x"" ] ; then
		/sbin/mx-overlay $DIR
	fi
done < $READFILE

mount -o remount,ro /

# ----- Execute systemd -----
exec /lib/systemd/systemd $@

