#!/bin/bash
# This is a moxa-init loader
# For moxa-init-main self upgrade
ARGS="$@"
UPGRADE_FILE="/overlayfs/moxa-init-main"
MOXA_INIT_MAIN_FILE="/sbin/moxa-init-main"

mount -o remount,rw /

# Get RFS partition from cmdline. e.g. /dev/mmcblk0p2
ROOT_PART=$(dmesg | grep "Kernel command line")
ROOT_PART="${ROOT_PART##*root=}"
ROOT_PART="${ROOT_PART%% *}"
ROOT_PART="${ROOT_PART%%2}3"

# mount RFS partition3 to /overlayfs
if [ ! -d /overlayfs ]; then
	mkdir /overlayfs
fi
mount $ROOT_PART /overlayfs

# check upgrade file & self upgrade
self_upgrade () {
	if [ -f "$UPGRADE_FILE" ]; then
		echo "Found a new version of moxa-init, updating..."
		mv "$UPGRADE_FILE" "$MOXA_INIT_MAIN_FILE"
		echo "Update moxa-init successful"
	fi
}

# main function
main(){
	exec $MOXA_INIT_MAIN_FILE $ARGS
}

self_upgrade
main
