#!/bin/bash

TMP_RFS_P1=/dev/shm/rfs_p1
KERNEL_PART=$(cat /proc/cmdline)
KERNEL_PART="${KERNEL_PART##*root=}"
KERNEL_PART="${KERNEL_PART%% *}"
KERNEL_PART="${KERNEL_PART%%2}1"

downgrade(){
	rm -rf /overlayfs/v1
	cp -ar /overlayfs/v0 /overlayfs/v1
	sync
}

main(){
	# S1 state
	## backup partition 1 kernel
	mkdir ${TMP_RFS_P1}

	# if p1 is already mount, umount it.
	if df -h | grep "${KERNEL_PART}" > /dev/null; then
		umount ${KERNEL_PART}
	fi
	mount ${KERNEL_PART} ${TMP_RFS_P1}
	cp -ar ${TMP_RFS_P1}/* /overlayfs/v1/p1/

	## backup v1
	cp -ar /overlayfs/v1 /overlayfs/backup

	# S2 state
	sync
	fw_setenv overlay_flag v1backup

	# S3 state
	downgrade
	sync
	fw_setenv overlay_flag v0

	# S4 state
	## rollback v0 partition 1 kernel
	mv /overlayfs/v0/p1/* ${TMP_RFS_P1}/
	umount ${TMP_RFS_P1}
	rm -rf /overlayfs/v0
	## rollback v0
	cp -ar /overlayfs/backup /overlayfs/v0
	sync
	fw_setenv overlay_flag v1d

	# S5 state
	reboot
}

main
