#!/bin/bash

TMP_RFS_P1=/dev/shm/rfs_p1
KERNEL_PART=$(cat /proc/cmdline)
KERNEL_PART="${KERNEL_PART##*root=}"
KERNEL_PART="${KERNEL_PART%% *}"
KERNEL_PART="${KERNEL_PART%%2}1"

upgrade(){
	apt-get upgrade
	sync
}

main(){
	# S1 state
	## backup partition 1 kernel
	mkdir ${TMP_RFS_P1}
	mount ${KERNEL_PART} ${TMP_RFS_P1}
	cp -ar ${TMP_RFS_P1}/* /overlayfs/v1/p1/
	umount ${TMP_RFS_P1}
	## backup v1
	cp -ar /overlayfs/v1 /overlayfs/backup

	# S2 state
	sync
	fw_setenv overlay_flag v1backup

	# S3 state
	upgrade
	sync
	fw_setenv overlay_flag v3

	# S4 state
	rm -rf /overlayfs/v0
	cp -ar /overlayfs/backup /overlayfs/v0
	sync
	fw_setenv overlay_flag v1u

	# S5 state
	reboot
}

main
