#!/bin/bash

# get overlay DIR
DIR="$1"

# get flag from spi flash
eval "$(fw_printenv|grep overlay_flag)"

check_folder() {
	local folder=${1}

	if [ ! -d ${folder} ]; then
		mkdir -p ${folder}
        fi
}

# ----- flag=v1 -----
if [ x"$overlay_flag" == x"v1" ]; then
	if [ -d "/overlayfs/backup" ]; then
		rm -rf "/overlayfs/backup"
	fi
	
	# make sure the overlay folders are exist.
	check_folder "${DIR}"
	check_folder "/overlayfs/v1/${DIR}_rw/upper"
	check_folder "/overlayfs/v1/${DIR}_rw/work"
	
	OPTS="-o lowerdir=${DIR},upperdir=/overlayfs/v1/${DIR}_rw/upper,workdir=/overlayfs/v1/${DIR}_rw/work"
	/bin/mount -t overlay ${OPTS} overlay ${DIR}
else
	exit
fi
