#!/bin/bash

TMP_RFS_P1="/dev/shm/rfs_p1"
OVERLAY_P1="/overlayfs/base"

KERNEL_PART=$(cat /proc/cmdline)
KERNEL_PART="${KERNEL_PART##*root=}"
KERNEL_PART="${KERNEL_PART%% *}"
KERNEL_PART="${KERNEL_PART%%2}1"

# set to default kernel
mkdir -p ${TMP_RFS_P1}
mkdir -p ${OVERLAY_P1}

# restore p1 if p1 backup files are exist
if [ -n "$(ls -A ${OVERLAY_P1})" ]; then
	# Due to the improper operation on an image generation,
	# the folder 'lost+found' exists under OVERLAY_P1.
	# Remove it if found.
	if [ -d "${OVERLAY_P1}/lost+found" ]; then
		rm -rf "${OVERLAY_P1}/lost+found"
	fi

	# if p1 is already mount, umount it.
	if df -h | grep -q "${KERNEL_PART}"; then
		umount ${KERNEL_PART}
	fi
	mount ${KERNEL_PART} ${TMP_RFS_P1}
	cp ${OVERLAY_P1}/* ${TMP_RFS_P1}/
	sync
	umount ${KERNEL_PART}
fi

# prepare to set to default root file system
fw_setenv overlay_flag default
reboot
