#!/bin/bash

# get overlay DIR
DIR="$1"

# get flag from spi flash
eval "$(fw_printenv|grep overlay_flag)"

# ----- flag=v1 -----
if [ x"$overlay_flag" == x"v1" ]; then
	if [ -d "/overlayfs/backup" ]; then
		rm -rf "/overlayfs/backup"
	fi
	
	if [ ! -d "/overlayfs/v1/${DIR}_rw" ]
	then
	    echo "/overlayfs/v1/${DIR}_rw does not exist" >&2
	    exit 1
	fi
	
	OPTS="-o lowerdir=${DIR},upperdir=/overlayfs/v1/${DIR}_rw/upper,workdir=/overlayfs/v1/${DIR}_rw/work"
	/bin/mount -t overlay ${OPTS} overlay ${DIR}
else
	exit
fi
