#!/bin/bash

READFILE="/etc/moxa-configs/moxa-set-default.conf"

mount -o remount,rw /

# get flag from spi flash
eval "$(fw_printenv|grep overlay_flag)"

# Engineer debug mode
if [ x"$overlay_flag" == x"debug" ]; then
	exit
fi

# Get RFS partition from cmdline. e.g. /dev/mmcblk0p2
ROOT_PART=$(cat /proc/cmdline)
ROOT_PART="${ROOT_PART##*root=}"
ROOT_PART="${ROOT_PART%% *}"
ROOT_PART="${ROOT_PART%%2}3"
# mount RFS partition3 to /overlayfs
mount $ROOT_PART /overlayfs

# ----- flag=v1backup -----
if [ x"$overlay_flag" == x"v1backup" ]; then
	rm -rf /overlayfs/v1
	cp -ar /overlayfs/backup /overlayfs/v1
	sync
	fw_setenv overlay_flag v1
	echo "upgrade failed" > /dev/ttyS0
	reboot
	exit
fi

# ----- flag=v0 -----
if [ x"$overlay_flag" == x"v0" ]; then
	echo "restore downgrade status" > /dev/ttyS0
	rm -rf /overlayfs/v0
	cp -ar /overlayfs/backup /overlayfs/v0
	sync
	fw_setenv overlay_flag v1d
	reboot
	exit
fi

# ----- flag=v3 -----
if [ x"$overlay_flag" == x"v3" ]; then
	echo "restore upgrade status" > /dev/ttyS0
	rm -rf /overlayfs/v0
	cp -ar /overlayfs/backup /overlayfs/v0
	sync
	fw_setenv overlay_flag v1u
	reboot
	exit
fi

# ----- flag=v1u -----
if [ x"$overlay_flag" == x"v1u" ]; then
	rm -rf /overlayfs/backup
	sync
	echo "upgrade successful" > /dev/ttyS0
	fw_setenv overlay_flag v1
fi

# ----- flag=v1d -----
if [ x"$overlay_flag" == x"v1d" ]; then
	rm -rf /overlayfs/backup
	sync
	echo "downgrade successful" > /dev/ttyS0
	fw_setenv overlay_flag v1
fi

# ----- flag=default -----
if [ x"$overlay_flag" == x"default" ]; then
	rm -rf /overlayfs/v1
	cp -ar /overlayfs/default /overlayfs/v1
	sync
	echo "set to default successful" > /dev/ttyS0
	fw_setenv overlay_flag v1
fi

# ----- Run overlayfs -----
while read DIR; do
	if [ x"${DIR:0:1}" != x"#" ]&&[ x"${DIR:0:1}" != x"" ] ; then
		/sbin/mx-overlay $DIR
	fi
done < $READFILE

# ----- Execute systemd -----
exec /lib/systemd/systemd $@

