#!/bin/bash

downgrade(){
	rm -rf /overlayfs/v1
	cp -ar /overlayfs/v0 /overlayfs/v1
	sync
}

main(){
	# S1 state
	cp -ar /overlayfs/v1 /overlayfs/backup

	# S2 state
	sync
	fw_setenv overlay_flag v1backup

	# S3 state
	downgrade
	sync
	fw_setenv overlay_flag v0

	# S4 state
	rm -rf /overlayfs/v0
	cp -ar /overlayfs/backup /overlayfs/v0
	sync
	fw_setenv overlay_flag v1d

	# S5 state
	reboot
}

main
