#!/bin/bash

upgrade(){
	apt-get upgrade
	sync
}

# S1
cp -ar /overlayfs/v1 /overlayfs/backup

# S2
sync
fw_setenv overlay_flag v1backup

# S3
upgrade
sync
fw_setenv overlay_flag v3

# S4
rm -rf /overlayfs/v0
cp -ar /overlayfs/backup /overlayfs/v0
sync
fw_setenv overlay_flag v1u

# S5
reboot
