#!/bin/bash

upgrade(){
	apt-get upgrade
	sync
}

main(){
	# S1 state
	cp -ar /overlayfs/v1 /overlayfs/backup

	# S2 state
	sync
	fw_setenv overlay_flag v1backup

	# S3 state
	upgrade
	sync
	fw_setenv overlay_flag v3

	# S4 state
	rm -rf /overlayfs/v0
	cp -ar /overlayfs/backup /overlayfs/v0
	sync
	fw_setenv overlay_flag v1u

	# S5 state
	reboot
}

main
