#!/bin/bash
DIR="$1"
#echo "$(date) $DIR" >> /home/moxa/test
# get flag from spi flash
eval "$(fw_printenv|grep overlay_flag)"

while [ -f /tmp/.overlay.lock ]
do
	sleep 0.1
done

#if [ x"$overlay_flag" != x"v1" ] && [ x"$DIR" == x"/overlayfs" ]; then
if [ x"$overlay_flag" != x"v1" ]; then
	exit
fi

# ----- flag=v1 -----
if [ x"$overlay_flag" == x"v1" ]; then
	if [ -d "/overlayfs/backup" ]; then
		rm -rf "/overlayfs/backup"
	fi
	
	if [ ! -d "/overlayfs/v1/${DIR}_rw" ]
	then
	    echo "/overlayfs/v1/${DIR}_rw does not exist" >&2
	    exit 1
	fi
	
	OPTS="-o lowerdir=${DIR},upperdir=/overlayfs/v1/${DIR}_rw/upper,workdir=/overlayfs/v1/${DIR}_rw/work"
	/bin/mount -t overlay ${OPTS} overlay ${DIR}
fi
